//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticalWork18
{
    using System;
    using System.Collections.Generic;
    
    public partial class Finals
    {
        public int Id { get; set; }
        public string GroupId { get; set; }
        public string FullName { get; set; }
        public string Gender { get; set; }
        public string MaritalStatus { get; set; }
        public Nullable<int> Exam1 { get; set; }
        public Nullable<int> Exam2 { get; set; }
        public Nullable<int> Exam3 { get; set; }
        public Nullable<int> Exam4 { get; set; }
        public Nullable<int> Exam5 { get; set; }
    }
}
